config/routes.rb
Rails.application.routes.draw do

  get 'teachers/edit'

  get 'session/login'

  get 'session/logout'

  post 'session/login'

  root 'session#login'

  resources :teachers

  resources :parents

end

app/models/parent.rb
class Parent < ActiveRecord::Base
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_secure_password
  has_many :parents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :check_login
  before_action :set_parent, only: [:show, :edit, :update, :destroy]
  # GET /parents
  # GET /parents.json
  def index
    @parents = Parent.all
    @teacher = Teacher.find_by_id(session[:user_id])
  end

  # GET /parents/1
  # GET /parents/1.json
  def show
  end

  # GET /parents/new
  def new
    @parent = Parent.new
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render :show, status: :created, location: @parent }
      else
        format.html { render :new }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1
  # PATCH/PUT /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url, notice: 'Parent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:name, :email, :teacher_id)

    end

    def check_login
      if session[:user_id]
        return true
      else
        redirect_to session_login_path, notice: "Please Log In"
      end
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def login
    if request.post?
      teacher = Teacher.find_by_email(params[:email])
      if teacher && teacher.authenticate(params[:password])
        session[:user_id] = teacher.id
        redirect_to parents_path, notice: "Successfully logged in."
      else
        redirect_to root_path, notice: "Please Try Again"
      end
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to session_login_path, notice: "Successfully logged out."
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:edit, :update]

  def edit
    # @teacher = Teacher.find_by_id(session[:user_id])
  end

  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to parents_path, notice: 'Teacher was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def teacher_params
      params.require(:teacher).permit(:password, :email, :name)
    end

    def set_teacher
      @teacher = Teacher.find_by_id(session[:user_id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teacherbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<% if session[:user_id] %>
  <header>
    <h3>Hello <%= Teacher.find_by_id(session[:user_id]).name %>!  <%= link_to 'Edit Profile', edit_teacher_path(Teacher.find_by_id(session[:user_id])) %></h3>
  </header>
<% end %>
<body>


<p id="notice"><%= notice %></p>


<%= yield %>

</body>
<footer>
  <%= link_to 'Logout', session_logout_path %>
</footer>
</html>

app/views/parents/_form.html.erb
<%= form_for(@parent) do |f| %>
  <% if @parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% @parent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :teacher_id %><br>
    <%= f.hidden_field :teacher_id, :value => session[:user_id] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing Parent</h1>

<%= render 'form' %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<h1>Listing Parents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teacher.parents.each do |parent| %>
      <tr>
        <td><%= parent.name %></td>
        <td><%= parent.email %></td>
        <td><%= link_to 'Show', parent %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<h1>New Parent</h1>

<%= render 'form' %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @parent.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @parent.email %>
</p>

<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>

app/views/session/login.html.erb
<h1>Please Login</h1>
<%= form_tag do %>

  <%= label_tag :email %>
  <%= text_field_tag :email %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= submit_tag "Login" %>

<% end %>

app/views/teachers/edit.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>